

import { Language, CropPrice } from './types';

export const APP_NAME = "InnoSphere";

export const TRANSLATIONS = {
  [Language.ENGLISH]: {
    welcome: "Welcome to InnoSphere",
    selectLang: "Select Language",
    dashboard: "Farm Dashboard",
    chat: "Krishi Sakhi",
    scan: "Pest Doctor",
    market: "Mandi Prices",
    profile: "Profile",
    weather: "Weather",
    soilHealth: "Soil Health",
    pestRisk: "Pest Risk",
    good: "Good",
    alert: "Alert",
    safe: "Safe",
    actionRequired: "Action Required",
    todayAdvisory: "Today's Advisory",
    typeMessage: "Type or speak...",
    uploadImage: "Upload Leaf Photo",
    analyzing: "Analyzing...",
    diagnosis: "Diagnosis",
    remedy: "Remedy",
    sustainability: "Sustainability Score",
    waterSaved: "Water Saved",
    login: "Login",
    submit: "Submit",
    loginWithOtp: "Login with OTP",
    loginWithPass: "Password Login",
    signup: "Sign Up",
    createAccount: "Create Account",
    name: "Full Name",
    mobile: "Mobile Number",
    email: "Email ID (Optional)",
    village: "Village / City",
    pincode: "Pincode",
    password: "Password",
    confirmPassword: "Confirm Password",
    getOtp: "Get OTP",
    enterOtp: "Enter OTP",
    haveAccount: "Already have an account? Login",
    noAccount: "New here? Create Account",
    otp: "OTP",
    otpSent: "OTP Sent",
    invalidMobile: "Invalid Mobile Number",
    enterCropName: "Enter Crop Name (Optional)",
    analyze: "Analyze Disease",
    // New Onboarding Translations
    completeProfile: "Complete Your Farm Profile",
    farmDetails: "Farm Details",
    farmLocation: "Farm Location",
    locateMe: "Locate Me",
    farmAddress: "Farm Address / Landmark",
    farmSize: "Farm Size",
    unit: "Unit",
    soilType: "Soil Type",
    cropHistory: "Crop History",
    addCrop: "Add Crop",
    cropName: "Crop Name",
    season: "Season",
    saveProfile: "Save Profile",
    skip: "Skip for Now",
    locationCaptured: "Location Captured",
    // Soil Health
    soilHealthCard: "Soil Health Card",
    uploadSoilCard: "Upload Soil Health Card",
    findLabs: "Find Nearest Soil Testing Lab",
    noCardUploaded: "No Soil Health Card uploaded yet.",
    viewCard: "View Card",
    deleteCard: "Delete",
    existingCard: "Your Soil Health Card",
    uploadSuccess: "Card uploaded successfully!",
    // Recommendations
    recommendations: "Crop Advisor",
    getRecommendations: "Get AI Recommendations",
    generatingPlan: "Generating precision farming plan...",
    matchScore: "Match Score",
    viewTimeline: "View Timeline",
    farmPlan: "Farm Plan",
    days: "Days",
    // Pest Doctor Save Features
    saveReport: "Save Report",
    savedReports: "Saved Reports",
    viewFullContent: "View Full Content",
    reportSaved: "Report Saved Successfully",
    savedOn: "Saved On",
    // Tour Guide
    tourWelcomeTitle: "Welcome to Digital Kheti!",
    tourWelcomeDesc: "Let's take a quick tour to help you get the most out of your new smart farming companion.",
    tourDashboardTitle: "Farm Dashboard",
    tourDashboardDesc: "See your daily farm summary, live crop monitoring, and important weather alerts all in one place.",
    tourPestTitle: "Pest Doctor",
    tourPestDesc: "Take a photo of any sick plant. Our AI will instantly identify diseases and suggest remedies.",
    tourMandiTitle: "Mandi Prices",
    tourMandiDesc: "Check real-time market prices for your crops from nearby mandis to get the best value.",
    tourSoilTitle: "Soil Health",
    tourSoilDesc: "Upload your Soil Health Card to get simplified, AI-powered analysis and fertilizer tips.",
    tourAdviseTitle: "Crop Advisor",
    tourAdviseDesc: "Get personalized crop calendars and precision farming schedules tailored to your soil.",
    tourChatTitle: "Krishi Sakhi",
    tourChatDesc: "Have questions? Chat with our AI assistant anytime in your local language.",
    // Form Options
    soilTypes: {
      blackCotton: "Black Cotton",
      alluvial: "Alluvial",
      red: "Red",
      sandy: "Sandy",
      loamy: "Loamy",
      clay: "Clay"
    },
    irrigationTypes: {
      rainfed: "Rainfed",
      borewell: "Borewell",
      canal: "Canal",
      drip: "Drip",
      sprinkler: "Sprinkler",
      well: "Open Well",
      river: "River/Lake"
    },
    seasonTypes: {
      kharif: "Kharif (Monsoon)",
      rabi: "Rabi (Winter)",
      zaid: "Zaid (Summer)",
      annual: "Annual"
    },
    guidance: {
      address: { title: "Farm Location", text: "Drag the map pin to point exactly where your field is. This helps us give you hyper-local weather alerts." },
      farmSize: { title: "Farm Size", text: "Enter the total land area you have available for cultivation." },
      soilType: { title: "Soil Type", text: "Select how your soil feels. 'Black Cotton' is sticky when wet. 'Sandy' feels gritty." },
      irrigation: { title: "Irrigation Source", text: "Select 'Rainfed' if you rely only on monsoon, or choose your main water source." },
      cropName: { title: "Previous Crop", text: "Which crop did you grow last season? (e.g., Cotton, Soybean). Helps in crop rotation advice." },
      season: { title: "Season", text: "In which season was this crop harvested? Kharif is Monsoon, Rabi is Winter." },
      year: { title: "Harvest Year", text: "Select the year when this crop was harvested. This builds your farm's history." },
      yield: { title: "Crop Yield", text: "How much total produce did you get? Enter the value and select the unit." },
      area: { title: "Cultivated Area", text: "How much of your land was used for this specific crop?" }
    }
  },
  [Language.HINDI]: {
    welcome: "इनोस्फीयर में आपका स्वागत है",
    selectLang: "भाषा चुनें",
    dashboard: "फार्म डैशबोर्ड",
    chat: "कृषि सखी",
    scan: "कीट डॉक्टर",
    market: "मंडी भाव",
    profile: "प्रोफ़ाइल",
    weather: "मौसम",
    soilHealth: "मृदा स्वास्थ्य",
    pestRisk: "कीट जोखिम",
    good: "अच्छा",
    alert: "चेतावनी",
    safe: "सुरक्षित",
    actionRequired: "कार्रवाई आवश्यक",
    todayAdvisory: "आज की सलाह",
    typeMessage: "लिखें या बोलें...",
    uploadImage: "पत्ती की फोटो अपलोड करें",
    analyzing: "विश्लेषण हो रहा है...",
    diagnosis: "निदान",
    remedy: "उपाय",
    sustainability: "स्थिरता स्कोर",
    waterSaved: "पानी बचाया",
    login: "लॉगिन",
    submit: "जमा करें",
    loginWithOtp: "OTP से लॉगिन करें",
    loginWithPass: "पासवर्ड से लॉगिन करें",
    signup: "साइन अप",
    createAccount: "खाता बनाएं",
    name: "पूरा नाम",
    mobile: "मोबाइल नंबर",
    email: "ईमेल आईडी (वैकल्पिक)",
    village: "गाँव / शहर",
    pincode: "पिन कोड",
    password: "पासवर्ड",
    confirmPassword: "पासवर्ड की पुष्टि करें",
    getOtp: "OTP प्राप्त करें",
    enterOtp: "OTP दर्ज करें",
    haveAccount: "क्या आपके पास पहले से खाता है? लॉगिन करें",
    noAccount: "नये हैं? खाता बनाएं",
    otp: "OTP",
    otpSent: "OTP भेजा गया",
    invalidMobile: "अमान्य मोबाइल नंबर",
    enterCropName: "फसल का नाम दर्ज करें (वैकल्पिक)",
    analyze: "बीमारी की जाँच करें",
    completeProfile: "अपनी फ़ार्म प्रोफ़ाइल पूरी करें",
    farmDetails: "खेत का विवरण",
    farmLocation: "खेत का स्थान",
    locateMe: "मेरा स्थान पता करें",
    farmAddress: "खेत का पता / लैंडमार्क",
    farmSize: "खेत का आकार",
    unit: "इकाई",
    soilType: "मिट्टी का प्रकार",
    cropHistory: "फसल इतिहास",
    addCrop: "फसल जोड़ें",
    cropName: "फसल का नाम",
    season: "मौसम",
    saveProfile: "प्रोफ़ाइल सहेजें",
    skip: "अभी के लिए छोड़ें",
    locationCaptured: "स्थान लिया गया",
    soilHealthCard: "मृदा स्वास्थ्य कार्ड",
    uploadSoilCard: "मृदा स्वास्थ्य कार्ड अपलोड करें",
    findLabs: "निकटतम मिट्टी परीक्षण प्रयोगशाला खोजें",
    noCardUploaded: "अभी तक कोई कार्ड अपलोड नहीं किया गया।",
    viewCard: "कार्ड देखें",
    deleteCard: "हटाएं",
    existingCard: "आपका मृदा स्वास्थ्य कार्ड",
    uploadSuccess: "कार्ड सफलतापूर्वक अपलोड किया गया!",
    recommendations: "फसल सलाहकार",
    getRecommendations: "AI सुझाव प्राप्त करें",
    generatingPlan: "सटीक खेती योजना तैयार हो रही है...",
    matchScore: "मैच स्कोर",
    viewTimeline: "समयरेखा देखें",
    farmPlan: "खेती की योजना",
    days: "दिन",
    saveReport: "रिपोर्ट सहेजें",
    savedReports: "सहेजी गई रिपोर्ट",
    viewFullContent: "पूरी सामग्री देखें",
    reportSaved: "रिपोर्ट सफलतापूर्वक सहेजी गई",
    savedOn: "सहेजा गया",
    tourWelcomeTitle: "डिजिटल खेती में आपका स्वागत है!",
    tourWelcomeDesc: "आइए एक त्वरित दौरा करें ताकि आप अपने नए स्मार्ट खेती साथी का अधिकतम लाभ उठा सकें।",
    tourDashboardTitle: "फार्म डैशबोर्ड",
    tourDashboardDesc: "अपना दैनिक खेत सारांश, लाइव फसल निगरानी और महत्वपूर्ण मौसम अलर्ट एक ही जगह देखें।",
    tourPestTitle: "कीट डॉक्टर",
    tourPestDesc: "किसी भी बीमार पौधे की फोटो लें। हमारा AI तुरंत बीमारियों की पहचान करेगा और उपाय सुझाएगा।",
    tourMandiTitle: "मंडी भाव",
    tourMandiDesc: "सर्वोत्तम मूल्य प्राप्त करने के लिए अपनी फसलों के लिए वास्तविक समय के बाजार भाव देखें।",
    tourSoilTitle: "मृदा स्वास्थ्य",
    tourSoilDesc: "सरलीकृत, AI-संचालित विश्लेषण और उर्वरक सुझाव प्राप्त करने के लिए अपना मृदा स्वास्थ्य कार्ड अपलोड करें।",
    tourAdviseTitle: "फसल सलाहकार",
    tourAdviseDesc: "अपनी मिट्टी के लिए अनुकूलित व्यक्तिगत फसल कैलेंडर और सटीक खेती कार्यक्रम प्राप्त करें।",
    tourChatTitle: "कृषि सखी",
    tourChatDesc: "कोई सवाल है? अपनी स्थानीय भाषा में कभी भी हमारे AI सहायक से चैट करें।",
    soilTypes: {
      blackCotton: "काली मिट्टी (Black Cotton)",
      alluvial: "जलोढ़ मिट्टी (Alluvial)",
      red: "लाल मिट्टी (Red)",
      sandy: "रेतीली मिट्टी (Sandy)",
      loamy: "दोमट मिट्टी (Loamy)",
      clay: "चिकनी मिट्टी (Clay)"
    },
    irrigationTypes: {
      rainfed: "वर्षा आधारित (Rainfed)",
      borewell: "नलकूप (Borewell)",
      canal: "नहर (Canal)",
      drip: "ड्रिप (Drip)",
      sprinkler: "फव्वारा (Sprinkler)",
      well: "कुआँ (Well)",
      river: "नदी/तालाब (River)"
    },
    seasonTypes: {
      kharif: "खरीफ (मानसून)",
      rabi: "रबी (सर्दी)",
      zaid: "ज़ायद (गर्मी)",
      annual: "वार्षिक"
    },
    guidance: {
      address: { title: "खेत का स्थान", text: "अपने खेत के सटीक स्थान को इंगित करने के लिए मैप पिन को खींचें। इससे हमें आपको सटीक मौसम अलर्ट देने में मदद मिलती है।" },
      farmSize: { title: "खेत का आकार", text: "खेती के लिए उपलब्ध कुल भूमि क्षेत्र दर्ज करें।" },
      soilType: { title: "मिट्टी का प्रकार", text: "अपनी मिट्टी कैसी है, चुनें। 'काली मिट्टी' गीली होने पर चिपचिपी होती है। 'रेतीली' किरकिरी लगती है।" },
      irrigation: { title: "सिंचाई स्रोत", text: "यदि आप केवल मानसून पर निर्भर हैं तो 'वर्षा आधारित' चुनें, या अपना मुख्य जल स्रोत चुनें।" },
      cropName: { title: "पिछली फसल", text: "पिछली सीजन में आपने कौन सी फसल उगाई थी? (जैसे, कपास, सोयाबीन)। यह फसल चक्र सलाह में मदद करता है।" },
      season: { title: "मौसम", text: "यह फसल किस मौसम में काटी गई थी? खरीफ (मानसून), रबी (सर्दी), जायद (गर्मी)।" },
      year: { title: "फसल वर्ष", text: "वह वर्ष चुनें जब यह फसल काटी गई थी। यह आपके खेत का इतिहास बनाता है।" },
      yield: { title: "फसल की उपज", text: "आपको कुल कितनी उपज मिली? मान दर्ज करें और इकाई चुनें।" },
      area: { title: "खेती का क्षेत्र", text: "इस विशिष्ट फसल के लिए आपकी कितनी भूमि का उपयोग किया गया था?" }
    }
  },
  [Language.MARATHI]: {
    welcome: "इनोस्फीयर मध्ये आपले स्वागत आहे",
    selectLang: "भाषा निवडा",
    dashboard: "शेती डॅशबोर्ड",
    chat: "कृषी सखी",
    scan: "कीटक डॉक्टर",
    market: "मंडी भाव",
    profile: "प्रोफाइल",
    weather: "हवामान",
    soilHealth: "मृदा आरोग्य",
    pestRisk: "कीटक धोका",
    good: "चांगले",
    alert: "सतर्कता",
    safe: "सुरक्षित",
    actionRequired: "कृती आवश्यक",
    todayAdvisory: "आजचा सल्ला",
    typeMessage: "टाइप करा किंवा बोला...",
    uploadImage: "पानाचा फोटो अपलोड करा",
    analyzing: "विश्लेषण करत आहे...",
    diagnosis: "निदान",
    remedy: "उपाय",
    sustainability: "स्थिरता गुण",
    waterSaved: "पाणी वाचवले",
    login: "लॉगिन",
    submit: "सादर करा",
    loginWithOtp: "OTP द्वारे लॉगिन करा",
    loginWithPass: "पासवर्ड द्वारे लॉगिन करा",
    signup: "साइन अप",
    createAccount: "खाते तयार करा",
    name: "पूर्ण नाव",
    mobile: "मोबाईल नंबर",
    email: "ईमेल आयडी (वैकल्पिक)",
    village: "गाव / शहर",
    pincode: "पिन कोड",
    password: "पासवर्ड",
    confirmPassword: "पासवर्डची पुष्टी करा",
    getOtp: "OTP मिळवा",
    enterOtp: "OTP प्रविष्ट करा",
    haveAccount: "आधीच खाते आहे? लॉगिन करा",
    noAccount: "नवीन आहात? खाते तयार करा",
    otp: "OTP",
    otpSent: "OTP पाठवला",
    invalidMobile: "अवैध मोबाईल नंबर",
    enterCropName: "पिकाचे नाव प्रविष्ट करा (पर्यायी)",
    analyze: "रोगाची तपासणी करा",
    completeProfile: "आपली शेती प्रोफाइल पूर्ण करा",
    farmDetails: "शेती तपशील",
    farmLocation: "शेतीचे स्थान",
    locateMe: "माझे स्थान शोधा",
    farmAddress: "शेतीचा पत्ता / लँडमार्क",
    farmSize: "शेतीचा आकार",
    unit: "एकक",
    soilType: "मातीचा प्रकार",
    cropHistory: "पिकांचा इतिहास",
    addCrop: "पीक जोडा",
    cropName: "पिकाचे नाव",
    season: "हंगाम",
    saveProfile: "प्रोफाइल जतन करा",
    skip: "आत्तासाठी वगळा",
    locationCaptured: "स्थान घेतले",
    soilHealthCard: "मृदा आरोग्य पत्रिका",
    uploadSoilCard: "मृदा आरोग्य पत्रिका अपलोड करा",
    findLabs: "जवळची माती परीक्षण प्रयोगशाळा शोधा",
    noCardUploaded: "अद्याप कोणतीही पत्रिका अपलोड केलेली नाही.",
    viewCard: "पत्रिका पहा",
    deleteCard: "काढून टाका",
    existingCard: "तुमची मृदा आरोग्य पत्रिका",
    uploadSuccess: "पत्रिका यशस्वीरित्या अपलोड केली!",
    recommendations: "पीक सल्लागार",
    getRecommendations: "AI शिफारसी मिळवा",
    generatingPlan: "अचूक शेती योजना तयार करत आहे...",
    matchScore: "जुळणारा गुण",
    viewTimeline: "वेळापत्रक पहा",
    farmPlan: "शेती योजना",
    days: "दिवस",
    saveReport: "अहवाल जतन करा",
    savedReports: "जतन केलेले अहवाल",
    viewFullContent: "संपूर्ण सामग्री पहा",
    reportSaved: "अहवाल यशस्वीरित्या जतन केला",
    savedOn: "जतन केले",
    tourWelcomeTitle: "डिजिटल शेतीमध्ये आपले स्वागत आहे!",
    tourWelcomeDesc: "चला एक जलद फेरफटका मारूया जेणेकरून तुम्ही तुमच्या नवीन स्मार्ट शेती सोबतीचा जास्तीत जास्त फायदा घेऊ शकाल.",
    tourDashboardTitle: "शेती डॅशबोर्ड",
    tourDashboardDesc: "आपला दैनिक शेती सारांश, थेट पीक निरीक्षण आणि हवामान इशारे एकाच ठिकाणी पहा.",
    tourPestTitle: "कीटक डॉक्टर",
    tourPestDesc: "कोणत्याही आजारी रोपाचा फोटो काढा. आमचे AI त्वरित रोगांची ओळख पटेल आणि उपाय सुचवेल.",
    tourMandiTitle: "मंडी भाव",
    tourMandiDesc: "सर्वोत्तम दर मिळवण्यासाठी तुमच्या पिकांचे रिअल-टाइम बाजारभाव तपासा.",
    tourSoilTitle: "मृदा आरोग्य",
    tourSoilDesc: "सुलभ, AI-आधारित विश्लेषण आणि खत शिफारसी मिळवण्यासाठी तुमची मृदा आरोग्य पत्रिका अपलोड करा.",
    tourAdviseTitle: "पीक सल्लागार",
    tourAdviseDesc: "तुमच्या जमिनीसाठी अनुकूलित वैयक्तिक पीक दिनदर्शिका आणि अचूक शेती वेळापत्रक मिळवा.",
    tourChatTitle: "कृषी सखी",
    tourChatDesc: "काही प्रश्न आहेत? तुमच्या स्थानिक भाषेत कधीही आमच्या AI सहाय्यकाशी चॅट करा.",
    soilTypes: {
      blackCotton: "काळी मृदा (Black Cotton)",
      alluvial: "गाळाची मृदा (Alluvial)",
      red: "लाल मृदा (Red)",
      sandy: "वालुकामय मृदा (Sandy)",
      loamy: "पोयटा मृदा (Loamy)",
      clay: "चिकन मृदा (Clay)"
    },
    irrigationTypes: {
      rainfed: "जिरायती (Rainfed)",
      borewell: "बोअरवेल (Borewell)",
      canal: "कालवा (Canal)",
      drip: "ठिबक (Drip)",
      sprinkler: "तुषार (Sprinkler)",
      well: "विहीर (Well)",
      river: "नदी (River)"
    },
    seasonTypes: {
      kharif: "खरीप (पावसाळा)",
      rabi: "रब्बी (हिवाळा)",
      zaid: "उन्हाळी (उन्हाळा)",
      annual: "वार्षिक"
    },
    guidance: {
      address: { title: "शेतीचे स्थान", text: "तुमचे शेत नेमके कुठे आहे हे दाखवण्यासाठी नकाशा पिन ड्रॅग करा. हे आम्हाला तुम्हाला अचूक हवामान सूचना देण्यास मदत करते." },
      farmSize: { title: "शेतीचा आकार", text: "तुमच्याकडे लागवडीसाठी उपलब्ध असलेले एकूण क्षेत्र प्रविष्ट करा." },
      soilType: { title: "मातीचा प्रकार", text: "तुमची माती कशी आहे ते निवडा. 'काळी माती' ओली असताना चिकट असते. 'रेतीयुक्त' खडबडीत असते." },
      irrigation: { title: "सिंचन स्रोत", text: "जर तुम्ही फक्त मान्सूनवर अवलंबून असाल तर 'जिरायती' निवडा किंवा तुमचा मुख्य पाण्याचा स्रोत निवडा." },
      cropName: { title: "मागील पीक", text: "गेल्या हंगामात तुम्ही कोणते पीक घेतले होते? (उदा. कापूस, सोयाबीन). हे पीक फेरपालट सल्ल्यामध्ये मदत करते." },
      season: { title: "हंगाम", text: "हे पीक कोणत्या हंगामात काढले गेले? खरीप (पावसाळा), रब्बी (हिवाळा)." },
      year: { title: "पीक वर्ष", text: "पीक कधी काढले गेले ते वर्ष निवडा. हे तुमच्या शेतीचा इतिहास तयार करते." },
      yield: { title: "पीक उत्पादन", text: "तुम्हाला एकूण किती उत्पादन मिळाले? मूल्य प्रविष्ट करा आणि एकक निवडा." },
      area: { title: "लागवडीखालील क्षेत्र", text: "या विशिष्ट पिकासाठी तुमची किती जमीन वापरली गेली?" }
    }
  },
  [Language.TELUGU]: {
    welcome: "InnoSphere కి స్వాగతం",
    selectLang: "భాషను ఎంచుకోండి",
    dashboard: "ఫార్మ్ డ్యాష్‌బోర్డ్",
    chat: "కృషి సఖి",
    scan: "పెస్ట్ డాక్టర్",
    market: "మండి ధరలు",
    profile: "ప్రొఫైల్",
    weather: "వాతావరణం",
    soilHealth: "నేల ఆరోగ్యం",
    pestRisk: "తెగులు ముప్పు",
    good: "బాగుంది",
    alert: "హెచ్చరిక",
    safe: "సురక్షితం",
    actionRequired: "చర్య అవసరం",
    todayAdvisory: "నేటి సలహా",
    typeMessage: "టైప్ చేయండి లేదా మాట్లాడండి...",
    uploadImage: "ఆకు ఫోటో అప్‌లోడ్ చేయండి",
    analyzing: "విశ్లేషిస్తోంది...",
    diagnosis: "నిర్ధారణ",
    remedy: "పరిష్కారం",
    sustainability: "స్థిరత్వం స్కోరు",
    waterSaved: "నీరు ఆదా",
    login: "లాగిన్",
    submit: "సమర్పించు",
    loginWithOtp: "OTP తో లాగిన్",
    loginWithPass: "పాస్‌వర్డ్ లాగిన్",
    signup: "సైన్ అప్",
    createAccount: "ఖాతా సృష్టించండి",
    name: "పూర్తి పేరు",
    mobile: "మొబైల్ నంబర్",
    email: "ఇమెయిల్ (ఐచ్ఛికం)",
    village: "గ్రామం / నగరం",
    pincode: "పిన్ కోడ్",
    password: "పాస్‌వర్డ్",
    confirmPassword: "పాస్‌వర్డ్‌ని నిర్ధారించండి",
    getOtp: "OTP పొందండి",
    enterOtp: "OTP నమోదు చేయండి",
    haveAccount: "ఖాతా ఉందా? లాగిన్",
    noAccount: "కొత్తవారా? ఖాతా సృష్టించండి",
    otp: "OTP",
    otpSent: "OTP పంపబడింది",
    invalidMobile: "చెల్లని మొబైల్ సంఖ్య",
    enterCropName: "పంట పేరు నమోదు చేయండి (ఐచ్ఛికం)",
    analyze: "వ్యాధిని విశ్లేషించండి",
    completeProfile: "మీ వ్యవసాయ ప్రొఫైల్‌ను పూర్తి చేయండి",
    farmDetails: "వ్యవసాయ వివరాలు",
    farmLocation: "వ్యవసాయ స్థానం",
    locateMe: "నన్ను గుర్తించండి",
    farmAddress: "వ్యవసాయ చిరునామా",
    farmSize: "వ్యవసాయ పరిమాణం",
    unit: "యూనిట్",
    soilType: "నేల రకం",
    cropHistory: "పంట చరిత్ర",
    addCrop: "పంటను జోడించండి",
    cropName: "పంట పేరు",
    season: "సీజన్",
    saveProfile: "ప్రొఫైల్ సేవ్ చేయండి",
    skip: "ఇప్పటికి దాటవేయి",
    locationCaptured: "స్థానం తీసుకోబడింది",
    soilHealthCard: "సాయిల్ హెల్త్ కార్డ్",
    uploadSoilCard: "సాయిల్ హెల్త్ కార్డ్‌ని అప్‌లోడ్ చేయండి",
    findLabs: "దగ్గర్లో ఉన్న నేల పరీక్ష కేంద్రం",
    noCardUploaded: "కార్డ్ అప్‌లోడ్ చేయబడలేదు",
    viewCard: "కార్డ్ చూడండి",
    deleteCard: "తొలగించు",
    existingCard: "మీ సాయిల్ హెల్త్ కార్డ్",
    uploadSuccess: "కార్డ్ విజయవంతంగా అప్‌లోడ్ చేయబడింది",
    recommendations: "పంట సలహాదారు",
    getRecommendations: "AI సిఫార్సులను పొందండి",
    generatingPlan: "ఖచ్చితమైన వ్యవసాయ ప్రణాళికను రూపొందిస్తోంది...",
    matchScore: "మ్యాచ్ స్కోర్",
    viewTimeline: "టైమ్‌లైన్ చూడండి",
    farmPlan: "వ్యవసాయ ప్రణాళిక",
    days: "రోజులు",
    saveReport: "నివేదికను సేవ్ చేయండి",
    savedReports: "సేవ్ చేయబడిన నివేదికలు",
    viewFullContent: "పూర్తి కంటెంట్‌ని వీక్షించండి",
    reportSaved: "నివేదిక విజయవంతంగా సేవ్ చేయబడింది",
    savedOn: "సేవ్ చేయబడింది",
    tourWelcomeTitle: "డిజిటల్ వ్యవసాయానికి స్వాగతం!",
    tourWelcomeDesc: "మీ కొత్త స్మార్ట్ వ్యవసాయ సహచరుడిని పూర్తిగా అర్థం చేసుకోవడానికి ఒక చిన్న టూర్ చేద్దాం.",
    tourDashboardTitle: "ఫార్మ్ డ్యాష్‌బోర్డ్",
    tourDashboardDesc: "మీ రోజువారీ వ్యవసాయ సారాంశం, పంట పర్యవేక్షణ మరియు ముఖ్యమైన వాతావరణ హెచ్చరికలను ఇక్కడ చూడండి.",
    tourPestTitle: "పెస్ట్ డాక్టర్",
    tourPestDesc: "వ్యాధి సోకిన మొక్క ఫోటో తీయండి. మా AI తక్షణమే వ్యాధులను గుర్తించి పరిష్కారాలను సూచిస్తుంది.",
    tourMandiTitle: "మండి ధరలు",
    tourMandiDesc: "ఉత్తమ ధరను పొందడానికి మీ పంటల కోసం రియల్ టైమ్ మార్కెట్ ధరలను తనిఖీ చేయండి.",
    tourSoilTitle: "నేల ఆరోగ్యం",
    tourSoilDesc: "AI విశ్లేషణ మరియు ఎరువుల చిట్కాలను పొందడానికి మీ సాయిల్ హెల్త్ కార్డ్‌ను అప్‌లోడ్ చేయండి.",
    tourAdviseTitle: "పంట సలహాదారు",
    tourAdviseDesc: "మీ నేలకు అనుగుణంగా వ్యక్తిగతీకరించిన పంట క్యాలెండర్‌లు మరియు వ్యవసాయ ప్రణాళికలను పొందండి.",
    tourChatTitle: "కృషి సఖి",
    tourChatDesc: "ఏవైనా ప్రశ్నలు ఉన్నాయా? ఎప్పుడైనా మీ స్థానిక భాషలో మా AI అసిస్టెంట్‌తో చాట్ చేయండి.",
    soilTypes: {
      blackCotton: "నల్లరేగడి నేల (Black Cotton)",
      alluvial: "ఒండ్రు నేల (Alluvial)",
      red: "ఎర్ర నేల (Red)",
      sandy: "ఇసుక నేల (Sandy)",
      loamy: "లోమీ నేల (Loamy)",
      clay: "బంకమట్టి నేల (Clay)"
    },
    irrigationTypes: {
      rainfed: "వర్షాధార (Rainfed)",
      borewell: "బోరుబావి (Borewell)",
      canal: "కాలువ (Canal)",
      drip: "బిందు సేద్యం (Drip)",
      sprinkler: "స్ప్రింక్లర్ (Sprinkler)",
      well: "బావి (Well)",
      river: "నది (River)"
    },
    seasonTypes: {
      kharif: "ఖరీఫ్ (వర్షాకాలం)",
      rabi: "రబీ (చలికాలం)",
      zaid: "జైద్ (వేసవి)",
      annual: "వార్షిక"
    },
    guidance: {
      address: { title: "వ్యవసాయ క్షేత్రం స్థానం", text: "మీ పొలం ఎక్కడ ఉందో ఖచ్చితంగా చూపించడానికి మ్యాప్ పిన్‌ను లాగండి. ఇది మీకు ఖచ్చితమైన వాతావరణ హెచ్చరికలను అందించడంలో సహాయపడుతుంది." },
      farmSize: { title: "పొలం పరిమాణం", text: "సాగుకు అందుబాటులో ఉన్న మొత్తం భూమిని నమోదు చేయండి." },
      soilType: { title: "నేల రకం", text: "మీ నేల ఎలా ఉందో ఎంచుకోండి. 'నల్లరేగడి' తడిగా ఉన్నప్పుడు జిగటగా ఉంటుంది. 'ఇసుక' గరుకుగా ఉంటుంది." },
      irrigation: { title: "సాగునీటి వనరు", text: "వర్షంపై ఆధారపడితే 'వర్షాధార' ఎంచుకోండి లేదా మీ ప్రధాన నీటి వనరును ఎంచుకోండి." },
      cropName: { title: "గత పంట", text: "గత సీజన్‌లో మీరు ఏ పంట పండించారు? (ఉదా. పత్తి, సోయాబీన్). ఇది పంట మార్పిడి సలహాలో సహాయపడుతుంది." },
      season: { title: "సీజన్", text: "ఈ పంట ఏ సీజన్‌లో కోయబడింది? ఖరీఫ్ (వర్షాకాలం), రబీ (చలికాలం)." },
      year: { title: "పంట సంవత్సరం", text: "ఈ పంటను ఏ సంవత్సరంలో కోశారో ఎంచుకోండి. ఇది మీ వ్యవసాయ చరిత్రను రూపొందిస్తుంది." },
      yield: { title: "పంట దిగుబడి", text: "మీకు మొత్తం ఎంత ఉత్పత్తి వచ్చింది? విలువను నమోదు చేసి యూనిట్‌ను ఎంచుకోండి." },
      area: { title: "సాగు విస్తీర్ణం", text: "ఈ నిర్దిష్ట పంటకు మీ భూమిలో ఎంత ఉపయోగించబడింది?" }
    }
  },
  [Language.TAMIL]: {
    welcome: "InnoSphere-க்கு வரவேற்கிறோம்",
    selectLang: "மொழியைத் தேர்ந்தெடுக்கவும்",
    dashboard: "பண்ணை பலகை",
    chat: "கிருஷி சகி",
    scan: "பூச்சி மருத்துவர்",
    market: "சந்தை விலைகள்",
    profile: "சுயவிவரம்",
    weather: "வானிலை",
    soilHealth: "மண் வளம்",
    pestRisk: "பூச்சி ஆபத்து",
    good: "நன்று",
    alert: "எச்சரிக்கை",
    safe: "பாதுகாப்பான",
    actionRequired: "நடவடிக்கை தேவை",
    todayAdvisory: "இன்றைய ஆலோசனை",
    typeMessage: "தட்டச்சு செய்யவும் அல்லது பேசவும்...",
    uploadImage: "இலை புகைப்படத்தை பதிவேற்றவும்",
    analyzing: "பகுப்பாய்வு செய்கிறது...",
    diagnosis: "கண்டறிதல்",
    remedy: "தீர்வு",
    sustainability: "நிலைத்தன்மை மதிப்பெண்",
    waterSaved: "நீர் சேமிக்கப்பட்டது",
    login: "உள்நுழைய",
    submit: "சமர்ப்பிக்க",
    loginWithOtp: "OTP மூலம் உள்நுழைய",
    loginWithPass: "கடவுச்சொல் மூலம் உள்நுழைய",
    signup: "பதிவு செய்க",
    createAccount: "கணக்கை உருவாக்கவும்",
    name: "முழு பெயர்",
    mobile: "மொபைல் எண்",
    email: "மின்னஞ்சல் (விருப்பத் தேர்வு)",
    village: "கிராமம் / நகரம்",
    pincode: "அஞ்சல் குறியீடு",
    password: "கடவுச்சொல்",
    confirmPassword: "கடவுச்சொல்லை உறுதிப்படுத்தவும்",
    getOtp: "OTP பெறவும்",
    enterOtp: "OTP உள்ளிடவும்",
    haveAccount: "ஏற்கனவே கணக்கு உள்ளதா? உள்நுழைய",
    noAccount: "புதியவரா? கணக்கை உருவாக்கவும்",
    otp: "OTP",
    otpSent: "OTP அனுப்பப்பட்டது",
    invalidMobile: "செல்லுபடியாகாத மொபைல் எண்",
    enterCropName: "பயிர் பெயரை உள்ளிடவும் (விருப்பத் தேர்வு)",
    analyze: "நோயை ஆய்வு செய்க",
    completeProfile: "உங்கள் பண்ணை சுயவிவரத்தை முடிக்கவும்",
    farmDetails: "பண்ணை விவரங்கள்",
    farmLocation: "பண்ணை இடம்",
    locateMe: "என்னை கண்டறியவும்",
    farmAddress: "பண்ணை முகவரி",
    farmSize: "பண்ணை அளவு",
    unit: "அலகு",
    soilType: "மண் வகை",
    cropHistory: "பயிர் வரலாறு",
    addCrop: "பயிரைச் சேர்க்கவும்",
    cropName: "பயிர் பெயர்",
    season: "பருவம்",
    saveProfile: "சுயவிவரத்தைச் சேமிக்கவும்",
    skip: "தவிர்க்கவும்",
    locationCaptured: "டம் பிடிக்கப்பட்டது",
    soilHealthCard: "மண் சுகாதார அட்டை",
    uploadSoilCard: "மண் சுகாதார அட்டையை பதிவேற்றவும்",
    findLabs: "அருகிலுள்ள மண் பரிசோதனை கூடம்",
    noCardUploaded: "அட்டை பதிவேற்றப்படவில்லை",
    viewCard: "அட்டையைப் பார்க்கவும்",
    deleteCard: "நீக்கு",
    existingCard: "உங்கள் மண் சுகாதார அட்டை",
    uploadSuccess: "அட்டை வெற்றிகரமாக பதிவேற்றப்பட்டது",
    recommendations: "பயிர் ஆலோசகர்",
    getRecommendations: "AI பரிந்துரைகளைப் பெறவும்",
    generatingPlan: "துல்லியமான விவசாயத் திட்டத்தை உருவாக்குகிறது...",
    matchScore: "பொருத்த மதிப்பெண்",
    viewTimeline: "காலவரிசையைப் பார்க்கவும்",
    farmPlan: "பண்ணை திட்டம்",
    days: "நாட்கள்",
    saveReport: "அறிக்கையைச் சேமி",
    savedReports: "சேமிக்கப்பட்ட அறிக்கைகள்",
    viewFullContent: "முழு உள்ளடக்கத்தையும் காண்க",
    reportSaved: "அறிக்கை வெற்றிகரமாக சேமிக்கப்பட்டது",
    savedOn: "சேமிக்கப்பட்டது",
    tourWelcomeTitle: "டிஜிட்டல் விவசாயத்திற்கு வரவேற்கிறோம்!",
    tourWelcomeDesc: "உங்கள் புதிய ஸ்மார்ட் விவசாயத் துணையை முழுமையாகப் பயன்படுத்த ஒரு சிறிய சுற்றுலாவை மேற்கொள்வோம்.",
    tourDashboardTitle: "பண்ணை பலகை",
    tourDashboardDesc: "உங்கள் தினசரி பண்ணை சுருக்கம், பயிர் கண்காணிப்பு மற்றும் வானிலை எச்சரிக்கைகளை இங்கே பார்க்கலாம்.",
    tourPestTitle: "பூச்சி மருத்துவர்",
    tourPestDesc: "பாதிக்கப்பட்ட செடியின் புகைப்படத்தை எடுக்கவும். எங்கள் AI உடனடியாக நோயைக் கண்டறிந்து தீர்வளிக்கும்.",
    tourMandiTitle: "சந்தை விலைகள்",
    tourMandiDesc: "சிறந்த விலையைப் பெற உங்கள் பயிர்களுக்கான சந்தை நிலவரங்களை சரிபார்க்கவும்.",
    tourSoilTitle: "மண் வளம்",
    tourSoilDesc: "AI பகுப்பாய்வு மற்றும் உர பரிந்துரைகளைப் பெற உங்கள் மண் சுகாதார அட்டையை பதிவேற்றவும்.",
    tourAdviseTitle: "பயிர் ஆலோசகர்",
    tourAdviseDesc: "உங்கள் மண்ணுக்கேற்ற தனிப்பயனாக்கப்பட்ட பயிர் நாட்காட்டி மற்றும் விவசாயத் திட்டங்களைப் பெறுங்கள்.",
    tourChatTitle: "கிருஷி சகி",
    tourChatDesc: "கேள்விகள் உள்ளதா? எப்போது வேண்டுமானாலும் உங்கள் மொழியில் எங்கள் AI உதவியாளருடன் பேசுங்கள்.",
    soilTypes: {
      blackCotton: "கரிசல் மண் (Black Cotton)",
      alluvial: "வண்டல் மண் (Alluvial)",
      red: "செம்மண் (Red)",
      sandy: "மணல் மண் (Sandy)",
      loamy: "களிமண் (Loamy)",
      clay: "களிமண் (Clay)"
    },
    irrigationTypes: {
      rainfed: "மானாவாரி (Rainfed)",
      borewell: "ஆழ்துளை கிணறு (Borewell)",
      canal: "கால்வாய் (Canal)",
      drip: "சொட்டு நீர் (Drip)",
      sprinkler: "தெளிப்பு நீர் (Sprinkler)",
      well: "கிணறு (Well)",
      river: "நதி (River)"
    },
    seasonTypes: {
      kharif: "காரிஃப் (பருவமழை)",
      rabi: "ரபி (குளிர்காலம்)",
      zaid: "ஜைத் (கோடை)",
      annual: "வருடாந்திர"
    },
    guidance: {
      address: { title: "பண்ணை இடம்", text: "உங்கள் நிலம் எங்குள்ளது என்பதைத் துல்லியமாகக் காட்ட வரைபட ஊசியை இழுக்கவும். இது துல்லியமான வானிலை எச்சரிக்கைகளை வழங்க உதவுகிறது." },
      farmSize: { title: "பண்ணை அளவு", text: "சாகுபடிக்கு உங்களிடம் உள்ள மொத்த நிலப்பரப்பை உள்ளிடவும்." },
      soilType: { title: "மண் வகை", text: "உங்கள் மண் எப்படி இருக்கிறது என்பதைத் தேர்ந்தெடுக்கவும். ஈரமாக இருக்கும்போது 'கரிசல் மண்' ஒட்டும்." },
      irrigation: { title: "நீர்ப்பாசன ஆதாரம்", text: "மழையை மட்டுமே நம்பியிருந்தால் 'மானாவாரி' என்பதைத் தேர்ந்தெடுக்கவும் அல்லது உங்கள் முக்கிய நீர் ஆதாரத்தைத் தேர்வுசெய்யவும்." },
      cropName: { title: "முந்தைய பயிர்", text: "கடந்த பருவத்தில் என்ன பயிர் செய்தீர்கள்? (எ.கா. பருத்தி, சோயாபீன்). இது பயிர் சுழற்சி ஆலோசனைக்கு உதவுகிறது." },
      season: { title: "பருவம்", text: "இப்பயிர் எந்த பருவத்தில் அறுவடை செய்யப்பட்டது? காரீஃப் (பருவமழை), ரபி (குளிர்காலம்)." },
      year: { title: "அறுவடை ஆண்டு", text: "இப்பயிர் அறுவடை செய்யப்பட்ட ஆண்டைத் தேர்ந்தெடுக்கவும். இது உங்கள் பண்ணை வரலாற்றை உருவாக்குகிறது." },
      yield: { title: "பயிர் மகசூல்", text: "உங்களுக்கு மொத்தம் எவ்வளவு மகசூல் கிடைத்தது? மதிப்பை உள்ளிட்டு அலகைத் தேர்ந்தெடுக்கவும்." },
      area: { title: "சாகுபடி பரப்பு", text: "இப்பயிருக்காக உங்கள் நிலத்தில் எவ்வளவு பயன்படுத்தப்பட்டது?" }
    }
  },
  [Language.KANNADA]: {
    welcome: "InnoSphere ಗೆ ಸ್ವಾಗತ",
    selectLang: "ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    dashboard: "ಕೃಷಿ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    chat: "ಕೃಷಿ ಸಖಿ",
    scan: "ಕೀಟ ವೈದ್ಯ",
    market: "ಮಂಡಿ ಬೆಲೆಗಳು",
    profile: "ಪ್ರೊಫೈಲ್",
    weather: "ಹವಾಮಾನ",
    soilHealth: "ಮಣ್ಣಿನ ಆರೋಗ್ಯ",
    pestRisk: "ಕೀಟದ ಅಪಾಯ",
    good: "ಉತ್ತಮ",
    alert: "ಎಚ್ಚರಿಕೆ",
    safe: "ಸುರಕ್ಷಿತ",
    actionRequired: "ಕ್ರಮ ಅಗತ್ಯವಿದೆ",
    todayAdvisory: "ಇಂದಿನ ಸಲಹೆ",
    typeMessage: "ಬರೆಯಿರಿ ಅಥವಾ ಮಾತನಾಡಿ...",
    uploadImage: "ಎಲೆಯ ಫೋಟೋ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
    analyzing: "ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ...",
    diagnosis: "ರೋಗನಿರ್ಣಯ",
    remedy: "ಪರಿಹಾರ",
    sustainability: "ಸುಸ್ಥಿರತೆ ಸ್ಕೋರ್",
    waterSaved: "ನೀರು ಉಳಿತಾಯ",
    login: "ಲಾಗಿನ್",
    submit: "ಸಲ್ಲಿಸಿ",
    loginWithOtp: "OTP ಲಾಗಿನ್",
    loginWithPass: "ಪಾಸ್‌ವರ್ಡ್ ಲಾಗಿನ್",
    signup: "ಸೈನ್ ಅಪ್",
    createAccount: "ಖಾತೆ ತೆರೆಯಿರಿ",
    name: "ಪೂರ್ಣ ಹೆಸರು",
    mobile: "ಮೊಬೈಲ್ ಸಂಖ್ಯೆ",
    email: "ಇಮೇಲ್ (ಐಚ್ಛಿಕ)",
    village: "ಗ್ರಾಮ / ನಗರ",
    pincode: "ಪಿನ್ ಕೋಡ್",
    password: "ಪಾಸ್‌ವರ್ಡ್",
    confirmPassword: "ಪಾಸ್‌ವರ್ಡ್ ದೃಢೀಕರಿಸಿ",
    getOtp: "OTP ಪಡೆಯಿರಿ",
    enterOtp: "OTP ನಮೂದಿಸಿ",
    haveAccount: "ಈಗಾಗಲೇ ಖಾತೆ ಇದೆಯೇ? ಲಾಗಿನ್",
    noAccount: "ಹೊಸಬರೇ? ಖಾತೆ ರಚಿಸಿ",
    otp: "OTP",
    otpSent: "OTP ಕಳುಹಿಸಲಾಗಿದೆ",
    invalidMobile: "ಅಮಾನ್ಯ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ",
    enterCropName: "ಬೆಳೆಯ ಹೆಸರು ನಮೂದಿಸಿ (ಐಚ್ಛಿಕ)",
    analyze: "ರೋಗವನ್ನು ವಿಶ್ಲೇಷಿಸಿ",
    completeProfile: "ನಿಮ್ಮ ಕೃಷಿ ಪ್ರೊಫೈಲ್ ಪೂರ್ಣಗೊಳಿಸಿ",
    farmDetails: "ಕೃಷಿ ವಿವರಗಳು",
    farmLocation: "ಕೃಷಿ ಸ್ಥಳ",
    locateMe: "ನನ್ನನ್ನು ಗುರುತಿಸಿ",
    farmAddress: "ಕೃಷಿ ವಿಳಾಸ",
    farmSize: "ಕೃಷಿ ಗಾತ್ರ",
    unit: "ಘಟಕ",
    soilType: "ಮಣ್ಣಿನ ವಿಧ",
    cropHistory: "ಬೆಳೆ ಇತಿಹಾಸ",
    addCrop: "ಬೆಳೆ ಸೇರಿಸಿ",
    cropName: "ಬೆಳೆ ಹೆಸರು",
    season: "ಋತು",
    saveProfile: "ಪ್ರೊಫೈಲ್ ಉಳಿಸಿ",
    skip: "ಈಗ ಬಿಟ್ಟುಬಿಡಿ",
    locationCaptured: "ಸ್ಥಳ ಸೆರೆಹಿಡಿಯಲಾಗಿದೆ",
    soilHealthCard: "ಮಣ್ಣಿನ ಆರೋಗ್ಯ ಕಾರ್ಡ್",
    uploadSoilCard: "ಮಣ್ಣಿನ ಆರೋಗ್ಯ ಕಾರ್ಡ್ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
    findLabs: "ಹತ್ತಿರದ ಮಣ್ಣು ಪರೀಕ್ಷಾ ಕೇಂದ್ರ",
    noCardUploaded: "ಕಾರ್ಡ್ ಅಪ್‌ಲೋಡ್ ಮಾಡಲಾಗಿಲ್ಲ",
    viewCard: "ಕಾರ್ಡ್ ವೀಕ್ಷಿಸಿ",
    deleteCard: "ಅಳಿಸಿ",
    existingCard: "ನಿಮ್ಮ ಮಣ್ಣಿನ ಆರೋಗ್ಯ ಕಾರ್ಡ್",
    uploadSuccess: "ಕಾರ್ಡ್ ಯಶಸ್ವಿಯಾಗಿ ಅಪ್‌ಲೋಡ್ ಆಗಿದೆ",
    recommendations: "ಬೆಳೆ ಸಲಹೆಗಾರ",
    getRecommendations: "AI ಶಿಫಾರಸುಗಳನ್ನು ಪಡೆಯಿರಿ",
    generatingPlan: "ನಿಖರವಾದ ಕೃಷಿ ಯೋಜನೆಯನ್ನು ರಚಿಸಲಾಗುತ್ತಿದೆ...",
    matchScore: "ಹೊಂದಾಣಿಕೆ ಸ್ಕೋರ್",
    viewTimeline: "ವೇಳಾಪಟ್ಟಿ ವೀಕ್ಷಿಸಿ",
    farmPlan: "ಕೃಷಿ ಯೋಜನೆ",
    days: "ದಿನಗಳು",
    saveReport: "ವರದಿ ಉಳಿಸಿ",
    savedReports: "ಉಳಿಸಿದ ವರದಿಗಳು",
    viewFullContent: "ಪೂರ್ಣ ವಿಷಯವನ್ನು ವೀಕ್ಷಿಸಿ",
    reportSaved: "ವರದಿಯನ್ನು ಯಶಸ್ವಿಯಾಗಿ ಉಳಿಸಲಾಗಿದೆ",
    savedOn: "ಉಳಿಸಲಾಗಿದೆ",
    tourWelcomeTitle: "ಡಿಜಿಟಲ್ ಕೃಷಿಗೆ ಸುಸ್ವಾಗತ!",
    tourWelcomeDesc: "ನಿಮ್ಮ ಹೊಸ ಸ್ಮಾರ್ಟ್ ಕೃಷಿ ಸಂಗಾತಿಯನ್ನು ಸಂಪೂರ್ಣವಾಗಿ ಬಳಸಿಕೊಳ್ಳಲು ತ್ವರಿತ ಪ್ರವಾಸ ಮಾಡೋಣ.",
    tourDashboardTitle: "ಕೃಷಿ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    tourDashboardDesc: "ನಿಮ್ಮ ದೈನಂದಿನ ಕೃಷಿ ಸಾರಾಂಶ, ಬೆಳೆ ಉಸ್ತುವಾರಿ ಮತ್ತು ಹವಾಮಾನ ಎಚ್ಚರಿಕೆಗಳನ್ನು ಇಲ್ಲಿ ವೀಕ್ಷಿಸಿ.",
    tourPestTitle: "ಕೀಟ ವೈದ್ಯ",
    tourPestDesc: "ಯಾವುದೇ ರೋಗಗ್ರಸ್ತ ಸಸ್ಯದ ಫೋಟೋ ತೆಗೆಯಿರಿ. ನಮ್ಮ AI ತಕ್ಷಣ ರೋಗವನ್ನು ಗುರುತಿಸಿ ಪರಿಹಾರ ನೀಡುತ್ತದೆ.",
    tourMandiTitle: "ಮಂಡಿ ಬೆಲೆಗಳು",
    tourMandiDesc: "ಉತ್ತಮ ಬೆಲೆ ಪಡೆಯಲು ನಿಮ್ಮ ಬೆಳೆಗಳಿಗಾಗಿ ನೈಜ ಸಮಯದ ಮಾರುಕಟ್ಟೆ ದರಗಳನ್ನು ಪರಿಶೀಲಿಸಿ.",
    tourSoilTitle: "ಮಣ್ಣಿನ ಆರೋಗ್ಯ",
    tourSoilDesc: "AI ವಿಶ್ಲೇಷಣೆ ಮತ್ತು ರಸಗೊಬ್ಬರ ಸಲಹೆಗಳನ್ನು ಪಡೆಯಲು ನಿಮ್ಮ ಮಣ್ಣಿನ ಆರೋಗ್ಯ ಕಾರ್ಡ್ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ.",
    tourAdviseTitle: "ಬೆಳೆ ಸಲಹೆಗಾರ",
    tourAdviseDesc: "ನಿಮ್ಮ ಮಣ್ಣಿಗೆ ಸೂಕ್ತವಾದ ವೈಯಕ್ತಿಕ ಬೆಳೆ ಕ್ಯಾಲೆಂಡರ್ ಮತ್ತು ಕೃಷಿ ಯೋಜನೆಗಳನ್ನು ಪಡೆಯಿರಿ.",
    tourChatTitle: "ಕೃಷಿ ಸಖಿ",
    tourChatDesc: "ಪ್ರಶ್ನೆಗಳಿವೆಯೇ? ಯಾವುದೇ ಸಮಯದಲ್ಲಿ ನಿಮ್ಮ ಭಾಷೆಯಲ್ಲಿ ನಮ್ಮ AI ಸಹಾಯಕರೊಂದಿಗೆ ಚಾಟ್ ಮಾಡಿ.",
    soilTypes: {
      blackCotton: "ಕಪ್ಪು ಮಣ್ಣು (Black Cotton)",
      alluvial: "ಮೆಕ್ಕಲು ಮಣ್ಣು (Alluvial)",
      red: "ಕೆಂಪು ಮಣ್ಣು (Red)",
      sandy: "ಮರಳು ಮಣ್ಣು (Sandy)",
      loamy: "ಲೋಮಿ ಮಣ್ಣು (Loamy)",
      clay: "ಜೇಡಿ ಮಣ್ಣು (Clay)"
    },
    irrigationTypes: {
      rainfed: "ಮಳೆಯಾಶ್ರಿತ (Rainfed)",
      borewell: "ಬೋರ್‌ವೆಲ್ (Borewell)",
      canal: "ಕಾಲುವೆ (Canal)",
      drip: "ಹನಿ ನೀರಾವರಿ (Drip)",
      sprinkler: "ತುಂತುರು (Sprinkler)",
      well: "ಬಾವಿ (Well)",
      river: "ನದಿ (River)"
    },
    seasonTypes: {
      kharif: "ಖಾರಿಫ್ (ಮುಂಗಾರು)",
      rabi: "ರಬಿ (ಚಳಿಗಾಲ)",
      zaid: "ಜೈದ್ (ಬೇಸಿಗೆ)",
      annual: "ವಾರ್ಷಿಕ"
    },
    guidance: {
      address: { title: "ಕೃಷಿ ಸ್ಥಳ", text: "ನಿಮ್ಮ ಹೊಲ ಎಲ್ಲಿದೆ ಎಂದು ನಿಖರವಾಗಿ ತೋರಿಸಲು ಮ್ಯಾಪ್ ಪಿನ್ ಎಳೆಯಿರಿ. ಇದು ನಿಖರವಾದ ಹವಾಮಾನ ಎಚ್ಚರಿಕೆಗಳನ್ನು ನೀಡಲು ಸಹಾಯ ಮಾಡುತ್ತದೆ." },
      farmSize: { title: "ಕೃಷಿ ಗಾತ್ರ", text: "ಕೃಷಿಗೆ ಲಭ್ಯವಿರುವ ಒಟ್ಟು ಭೂಮಿಯನ್ನು ನಮೂದಿಸಿ." },
      soilType: { title: "ಮಣ್ಣಿನ ವಿಧ", text: "ನಿಮ್ಮ ಮಣ್ಣು ಹೇಗಿದೆ ಎಂಬುದನ್ನು ಆಯ್ಕೆಮಾಡಿ. 'ಕಪ್ಪು ಮಣ್ಣು' ಒದ್ದೆಯಾದಾಗ ಜಿಗುಟಾಗಿರುತ್ತದೆ." },
      irrigation: { title: "ನೀರಾವರಿ ಮೂಲ", text: "ಮಳೆಯನ್ನು ಮಾತ್ರ ಅವಲಂಬಿಸಿದ್ದರೆ 'ಮಳೆಯಾಶ್ರಿತ' ಆಯ್ಕೆಮಾಡಿ ಅಥವಾ ನಿಮ್ಮ ಮುಖ್ಯ ನೀರಿನ ಮೂಲವನ್ನು ಆರಿಸಿ." },
      cropName: { title: "ಹಿಂದಿನ ಬೆಳೆ", text: "ಕಳೆದ ಋತುವಿನಲ್ಲಿ ನೀವು ಯಾವ ಬೆಳೆ ಬೆಳೆದಿದ್ದೀರಿ? (ಉದಾ. ಹತ್ತಿ, ಸೋಯಾಬೀನ್). ಇದು ಬೆಳೆ ಪರಿವರ್ತನೆ ಸಲಹೆಗೆ ಸಹಾಯ ಮಾಡುತ್ತದೆ." },
      season: { title: "ಋತು", text: "ಈ ಬೆಳೆಯನ್ನು ಯಾವ ಋತುವಿನಲ್ಲಿ ಕೊಯ್ಲು ಮಾಡಲಾಗಿದೆ? ಖಾರಿಫ್ (ಮುಂಗಾರು), ರಬಿ (ಚಳಿಗಾಲ)." },
      year: { title: "ಕೊಯ್ಲು ವರ್ಷ", text: "ಈ ಬೆಳೆಯನ್ನು ಕೊಯ್ಲು ಮಾಡಿದ ವರ್ಷವನ್ನು ಆಯ್ಕೆಮಾಡಿ. ಇದು ನಿಮ್ಮ ಕೃಷಿ ಇತಿಹಾಸವನ್ನು ನಿರ್ಮಿಸುತ್ತದೆ." },
      yield: { title: "ಬೆಳೆ ಇಳುವರಿ", text: "ನಿಮಗೆ ಒಟ್ಟು ಎಷ್ಟು ಇಳುವರಿ ಸಿಕ್ಕಿತು? ಮೌಲ್ಯವನ್ನು ನಮೂದಿಸಿ ಮತ್ತು ಘಟಕವನ್ನು ಆಯ್ಕೆಮಾಡಿ." },
      area: { title: "ಸಾಗುವಳಿ ಪ್ರದೇಶ", text: "ಈ ನಿರ್ದಿಷ್ಟ ಬೆಳೆಗೆ ನಿಮ್ಮ ಎಷ್ಟು ಭೂಮಿಯನ್ನು ಬಳಸಲಾಗಿದೆ?" }
    }
  },
  [Language.MALAYALAM]: {
    welcome: "InnoSphere-ലേക്ക് സ്വാഗതം",
    selectLang: "ഭാష തിരഞ്ഞെടുക്കുക",
    dashboard: "ഫാം ഡാഷ്ബോർഡ്",
    chat: "കൃഷി സഖി",
    scan: "കീട ഡോക്ടർ",
    market: "ചന്ത വിലകൾ",
    profile: "പ്രൊഫൈൽ",
    weather: "കാലാവസ്ഥ",
    soilHealth: "മണ്ണിന്റെ ആരോഗ്യം",
    pestRisk: "കീട സാധ്യത",
    good: "നല്ലത്",
    alert: "മുന്നറിയിപ്പ്",
    safe: "സുരക്ഷിതം",
    actionRequired: "നടപടി ആവശ്യമാണ്",
    todayAdvisory: "ഇന്നത്തെ ഉപദേശം",
    typeMessage: "ടൈപ്പ് ചെയ്യുക അല്ലെങ്കിൽ സംസാരിക്കുക...",
    uploadImage: "ഇലയുടെ ഫോട്ടോ അപ്‌ലോഡ് ചെയ്യുക",
    analyzing: "വിശകലനം ചെയ്യുന്നു...",
    diagnosis: "രോഗനിർണ്ണയം",
    remedy: "പരിഹാരം",
    sustainability: "സുಸ್ಥിരത സ്കോർ",
    waterSaved: "വെള്ളം ലാഭിച്ചു",
    login: "ലോഗിൻ",
    submit: "സമർപ്പിക്കുക",
    loginWithOtp: "OTP ലോഗിൻ",
    loginWithPass: "പാസ്‌വേഡ് ലോഗിൻ",
    signup: "സൈൻ അപ്പ്",
    createAccount: "അക്കൗണ്ട് സൃഷ്ടിക്കുക",
    name: "പൂർണ്ണ നാമം",
    mobile: "മൊബൈൽ നമ്പർ",
    email: "ഇമെയിൽ (ഓപ്ഷണൽ)",
    village: "ഗ്രാമം / നഗരം",
    pincode: "പിన్ കോഡ്",
    password: "പാസ്‌വേഡ്",
    confirmPassword: "പാസ്‌വേഡ് സ്ഥിരീകരിക്കുക",
    getOtp: "OTP നേടുക",
    enterOtp: "OTP നൽകുക",
    haveAccount: "അക്കൗണ്ട് ഉണ്ടോ? ലോഗിൻ",
    noAccount: "പുതിയ ആളാണോ? അക്കൗണ്ട് ഉണ്ടാക്കുക",
    otp: "OTP",
    otpSent: "OTP അയച്ചു",
    invalidMobile: "അസാധുവായ മൊബൈൽ നമ്പർ",
    enterCropName: "വിളയുടെ പേര് നൽകുക (ഓപ്ഷണൽ)",
    analyze: "രോഗം പരിശോധിക്കുക",
    completeProfile: "നിങ്ങളുടെ ഫാം പ്രൊഫൈൽ പൂർത്തിയാക്കുക",
    farmDetails: "ഫാം വിവരങ്ങൾ",
    farmLocation: "ഫാം സ്ഥാനം",
    locateMe: "എന്നെ കണ്ടെത്തുക",
    farmAddress: "ഫാം വിലാസം",
    farmSize: "ഫാം വലുപ്പം",
    unit: "യൂണിറ്റ്",
    soilType: "മണ്ണിന്റെ തരം",
    cropHistory: "വിള ചരിത്രം",
    addCrop: "വിള ചേർക്കുക",
    cropName: "വിളയുടെ പേര്",
    season: "സീസൺ",
    saveProfile: "പ്രൊഫൈൽ സംരക്ഷിക്കുക",
    skip: "ഇപ്പോൾ ഒഴിവാക്കുക",
    locationCaptured: "സ്ഥാനം പിടിച്ചെടുത്തു",
    soilHealthCard: "മണ്ണ് ആരോഗ്യ കാർഡ്",
    uploadSoilCard: "മണ്ണ് ആരോഗ്യ കാർഡ് അപ്‌ലോഡ് ചെയ്യുക",
    findLabs: "അടുത്തുള്ള മണ്ണ് പരിശോധന ലാബ്",
    noCardUploaded: "കാർഡ് അപ്‌ലോഡ് ചെയ്തിട്ടില്ല",
    viewCard: "കാർഡ് കാണുക",
    deleteCard: "നീക്കം ചെയ്യുക",
    existingCard: "നിങ്ങളുടെ മണ്ണ് ആരോഗ്യ കാർഡ്",
    uploadSuccess: "കാർഡ് വിജയകരമായി അപ്‌ലോഡ് ചെയ്തു",
    recommendations: "വിള ഉപദേശകൻ",
    getRecommendations: "AI ശുപാർശകൾ നേടുക",
    generatingPlan: "കൃത്യമായ കാർഷിക പദ്ധതി തയ്യാറാക്കുന്നു...",
    matchScore: "പൊരുത്ത സ്കോർ",
    viewTimeline: "ടൈംലൈൻ കാണുക",
    farmPlan: "ഫാം പ്ലാൻ",
    days: "ദിവസങ്ങൾ",
    saveReport: "റിപ്പോർട്ട് സേവ് ചെയ്യുക",
    savedReports: "സേവ് ചെയ്ത റിപ്പോർട്ടുകൾ",
    viewFullContent: "പൂർണ്ണ ഉള്ളടക്കം കാണുക",
    reportSaved: "റിപ്പോർട്ട് വിജയകരമായി സേവ് ചെയ്തു",
    savedOn: "സേവ് ചെയ്തത്",
    tourWelcomeTitle: "ഡിജിറ്റൽ കൃഷിയിലേക്ക് സ്വാഗതം!",
    tourWelcomeDesc: "നിങ്ങളുടെ പുതിയ സ്മാർട്ട് കാർഷിക സഹായിയെ പൂർണ്ണമായി ഉപയോഗിക്കാൻ നമുക്കൊരു ചെറിയ ടൂർ നടത്താം.",
    tourDashboardTitle: "ഫാം ഡാഷ്ബോർഡ്",
    tourDashboardDesc: "നിങ്ങളുടെ ദൈനംദിന കാർഷിക സംഗ്രഹം, വിള നിരീക്ഷണം, കാലാവസ്ഥ മുന്നറിയിപ്പുകൾ എന്നിവ ഇവിടെ കാണാം.",
    tourPestTitle: "കീട ഡോക്ടർ",
    tourPestDesc: "രോഗബാധിതമായ ചെടിയുടെ ഫോട്ടോ എടുക്കുക. ഞങ്ങളുടെ AI തൽക്ഷണം രോഗം തിരിച്ചറിഞ്ഞ് പരിഹാരം നിർദ്ദേശിക്കും.",
    tourMandiTitle: "ചന്ത വിലകൾ",
    tourMandiDesc: "മികച്ച വില ലഭിക്കാൻ നിങ്ങളുടെ വിളകൾക്കുള്ള വിപണി നിരക്കുകൾ തത്സമയം പരിശോധിക്കുക.",
    tourSoilTitle: "മണ്ണിന്റെ ആരോഗ്യം",
    tourSoilDesc: "AI വിശകലനവും വളം നിർദ്ദേശങ്ങളും ലഭിക്കാൻ നിങ്ങളുടെ മണ്ണ് ആരോഗ്യ കാർഡ് അപ്‌ലോഡ് ചെയ്യുക.",
    tourAdviseTitle: "വിള ഉപദേശകൻ",
    tourAdviseDesc: "നിങ്ങളുടെ മണ്ണിന് അനുയോജ്യമായ വിള കലണ്ടറും കാർഷിക പദ്ധതികളും നേടുക.",
    tourChatTitle: "കൃഷി സഖി",
    tourChatDesc: "സംശയങ്ങളുണ്ടോ? എപ്പോൾ വേണമെങ്കിലും നിങ്ങളുടെ ഭാഷയിൽ ഞങ്ങളുടെ AI സഹായിയുമായി ചാറ്റ് ചെയ്യുക.",
    soilTypes: {
      blackCotton: "കറുത്ത മണ്ണ് (Black Cotton)",
      alluvial: "എക്കൽ മണ്ണ് (Alluvial)",
      red: "ചുവന്ന മണ്ണ് (Red)",
      sandy: "മണൽ മണ്ണ് (Sandy)",
      loamy: "പശിമരാശി മണ്ണ് (Loamy)",
      clay: "കളിമണ്ണ് (Clay)"
    },
    irrigationTypes: {
      rainfed: "മഴയെ ആശ്രയിച്ചുള്ളത് (Rainfed)",
      borewell: "കുഴൽക്കിണർ (Borewell)",
      canal: "കനാൽ (Canal)",
      drip: "ഡ്രിപ്പ് (Drip)",
      sprinkler: "സ്പ്രിംഗ്ലർ (Sprinkler)",
      well: "കിണർ (Well)",
      river: "നദി (River)"
    },
    seasonTypes: {
      kharif: "ഖാരിഫ് (മഴക്കാലം)",
      rabi: "റാബി (ശീതകാലം)",
      zaid: "സൈദ് (വേനൽ)",
      annual: "വാർഷിക"
    },
    guidance: {
      address: { title: "ഫാം സ്ഥാനം", text: "നിങ്ങളുടെ ഫീൽഡ് എവിടെയാണെന്ന് കൃത്യമായി കാണിക്കാൻ മാപ്പ് പിൻ വലിച്ചിടുക. കൃത്യമായ കാലാവസ്ഥാ അറിയിപ്പുകൾ നൽകാൻ ഇത് സഹായിക്കുന്നു." },
      farmSize: { title: "ഫാം വലുപ്പം", text: "കൃഷിക്കായി നിങ്ങൾക്ക് ലഭ്യമായ മൊത്തം ഭൂമി രേഖപ്പെടുത്തുക." },
      soilType: { title: "മണ്ണിന്റെ തരം", text: "നിങ്ങളുടെ മണ്ണ് എങ്ങനെയുണ്ടെന്ന് തിരഞ്ഞെടുക്കുക. നനയുമ്പോൾ 'കറുത്ത മണ്ണ്' ഒട്ടിപ്പിടിക്കും." },
      irrigation: { title: "ജലസേചന ഉറവിടം", text: "മഴയെ മാത്രം ആശ്രയിക്കുന്നുവെങ്കിൽ 'മഴയെ ആശ്രയിച്ചുള്ളത്' തിരഞ്ഞെടുക്കുക അല്ലെങ്കിൽ നിങ്ങളുടെ പ്രധാന ജലസ്രോതസ്സ് തിരഞ്ഞെടുക്കുക." },
      cropName: { title: "മുൻ വിള", text: "കഴിഞ്ഞ സീസണിൽ നിങ്ങൾ ഏത് വിളയാണ് കൃഷി ചെയ്തത്? (ഉദാ. പരുത്തി, സോയാബീൻ). ഇത് വിള പരിക്രമണത്തിന് സഹായിക്കുന്നു." },
      season: { title: "സീസൺ", text: "ഏത് സീസണിലാണ് ഈ വിളവെടുപ്പ് നടത്തിയത്? ഖാരിഫ് (മഴക്കാലം), റാബി (ശീതകാലം)." },
      year: { title: "വിളവെടുപ്പ് വർഷം", text: "ഈ വിളവെടുത്ത വർഷം തിരഞ്ഞെടുക്കുക. ഇത് നിങ്ങളുടെ ഫാം ചരിത്രം നിർമ്മിക്കുന്നു." },
      yield: { title: "വിളവ്", text: "നിങ്ങൾക്ക് ആകെ എത്ര ഉൽപ്പന്നം ലഭിച്ചു? മൂല്യം നൽകി യൂണിറ്റ് തിരഞ്ഞെടുക്കുക." },
      area: { title: "കൃഷി സ്ഥലം", text: "ഈ പ്രത്യേക വിളയ്ക്കായി നിങ്ങളുടെ എത്ര ഭൂമി ഉപയോഗിച്ചു?" }
    }
  }
};

export const VOICE_PROMPTS = {
  [Language.ENGLISH]: {
    intro: "Namaste! I am here to help. Let's build your profile. First, where is your farm located? Please say your village or city name.",
    location_confirm: "Okay, finding ",
    size: "Got it. What is the size of your farm? For example, say '5 acres' or '2 hectares'.",
    soil: "What type of soil do you have? You can say Black, Red, Sandy, or Clay.",
    irrigation: "How do you irrigate your farm? Rainfed, Borewell, Canal, or Well?",
    finish: "Thank you. I have filled the details. Please review and click Save Profile."
  },
  [Language.HINDI]: {
    intro: "नमस्ते! मैं आपकी मदद कर सकती हूँ। सबसे पहले बताएं, आपका खेत कहां है? अपने गांव का नाम बताएं।",
    location_confirm: "ठीक है, ढूँढ रहा हूँ ",
    size: "ठीक है। आपके खेत का कुल आकार क्या है? उदाहरण के लिए, 5 एकड़।",
    soil: "आपकी मिट्टी किस प्रकार की है? काली, लाल, रेतीली या चिकनी?",
    irrigation: "आप सिंचाई कैसे करते हैं? बारिश, नलकूप या नहर?",
    finish: "धन्यवाद। मैंने विवरण भर दिया है। कृपया जांचें और 'प्रोफ़ाइल सहेजें' दबाएं।"
  },
  [Language.MARATHI]: {
    intro: "नमस्कार! मी मदत करू शकते. प्रथम, तुमचे शेत कोठे आहे? तुमच्या गावाचे नाव सांगा.",
    location_confirm: "ठीक आहे, शोधत आहे ",
    size: "ठीक आहे. तुमच्या शेतीचा आकार काय आहे? उदाहरणार्थ, ५ एकर.",
    soil: "तुमची माती कोणत्या प्रकारची आहे? काळी, लाल, वालुकामय किंवा चिकन?",
    irrigation: "तुम्ही पाणी कसे देता? पावसावर अवलंबून, बोअरवेल की कालवा?",
    finish: "धन्यवाद. मी माहिती भरली आहे. कृपया तपासा आणि 'प्रोफाइल जतन करा' दाबा."
  },
  [Language.TELUGU]: {
    intro: "నమస్కారం! నేను సహాయం చేయగలను. ముందుగా, మీ పొలం ఎక్కడ ఉంది? మీ ఊరి పేరు చెప్పండి.",
    location_confirm: "సరే, కనుగొంటున్నాను ",
    size: "సరే. మీ పొలం పరిమాణం ఎంత? ఉదాహరణకు, 5 ఎకరాలు.",
    soil: "మీ నేల రకం ఏమిటి? నల్లరేగడి, ఎర్ర నేల, లేదా ఇసుక నేల?",
    irrigation: "మీరు నీటి పారుదల ఎలా చేస్తారు? వర్షాధార, బోరుబావి లేదా కాలువ?",
    finish: "ధన్యవాదాలు. వివరాలు నింపబడ్డాయి. దయచేసి సరిచూసుకోండి మరియు సేవ్ చేయండి."
  },
  [Language.TAMIL]: {
    intro: "வணக்கம்! நான் உதவ இங்கே இருக்கிறேன். முதலில், உங்கள் பண்ணை எங்கே உள்ளது? உங்கள் ஊர் பெயரைச் சொல்லுங்கள்.",
    location_confirm: "சரி, தேடுகிறேன் ",
    size: "சரி. உங்கள் பண்ணையின் அளவு என்ன? உதாரணமாக, 5 ஏக்கர்.",
    soil: "உங்கள் மண் வகை என்ன? கரிசல், செம்மண் அல்லது மணல் மண்?",
    irrigation: "நீங்கள் எப்படி நீர் பாய்ச்சுகிறீர்கள்? மானாவாரி, ஆழ்துளை கிணறு அல்லது கால்வாய்?",
    finish: "நன்றி. விவரங்களை நிரப்பிவிட்டேன். சரிபார்த்து சேமிக்கவும்."
  },
  [Language.KANNADA]: {
    intro: "ನಮಸ್ಕಾರ! ನಾನು ಸಹಾಯ ಮಾಡಬಹುದು. ಮೊದಲಿಗೆ, ನಿಮ್ಮ ಹೊಲ ಎಲ್ಲಿದೆ? ನಿಮ್ಮ ಊರಿನ ಹೆಸರು ಹೇಳಿ.",
    location_confirm: "ಸರಿ, ಹುಡುಕುತ್ತಿದ್ದೇನೆ ",
    size: "ಸರಿ. ನಿಮ್ಮ ಹೊಲದ ಅಳತೆ ಎಷ್ಟು? ಉದಾಹರಣೆಗೆ, 5 ಎಕರೆ.",
    soil: "ನಿಮ್ಮ ಮಣ್ಣಿನ ವಿಧ ಯಾವುದು? ಕಪ್ಪು, ಕೆಂಪು ಅಥವಾ ಮರಳು ಮಣ್ಣು?",
    irrigation: "ನೀವು ನೀರಾವರಿ ಹೇಗೆ ಮಾಡುತ್ತೀರಿ? ಮಳೆ ಆಧಾರಿತ, ಬೋರ್‌ವೆಲ್ ಅಥವಾ ಕಾಲುವೆ?",
    finish: "ಧನ್ಯವಾದಗಳು. ವಿವರಗಳನ್ನು ಭರ್ತಿ ಮಾಡಿದ್ದೇನೆ. ದಯವಿಟ್ಟು ಪರಿಶೀಲಿಸಿ ಮತ್ತು ಉಳಿಸಿ."
  },
  [Language.MALAYALAM]: {
    intro: "നമസ്കാരം! എനിക്ക് സഹായിക്കാൻ കഴിയും. ആദ്യം, നിങ്ങളുടെ കൃഷിയിടം എവിടെയാണ്? നിങ്ങളുടെ സ്ഥലത്തിന്റെ പേര് പറയൂ.",
    location_confirm: "ശരി, കണ്ടെത്തുന്നു ",
    size: "ശരി. നിങ്ങളുടെ കൃഷിയിടത്തിന്റെ വലുപ്പം എത്രയാണ്? ഉദാഹരണത്തിന്, 5 ഏക്കർ.",
    soil: "നിങ്ങളുടെ മണ്ണ് ഏതുതരം ആണ്? കറുത്ത മണ്ണ്, ചുവന്ന മണ്ണ് അതോ മണൽ മണ്ണ്?",
    irrigation: "നിങ്ങൾ എങ്ങനെയാണ് നനയ്ക്കുന്നത്? മഴയെ ആശ്രയിച്ചുള്ളത്, കുഴൽക്കിണർ അതോ കനാൽ?",
    finish: "നന്ദി. വിവരങ്ങൾ നൽകിയിട്ടുണ്ട്. ദയവായി പരിശോധിച്ച് സേവ് ചെയ്യുക."
  }
};

export const VOICE_KEYWORDS = {
  soil: {
    black: ['black', 'cotton', 'kali', 'kaali', 'काली', 'నల్ల', 'கரிசல்', 'ಕಪ್ಪು', 'കറുത്ത', 'काळ्या'],
    red: ['red', 'lal', 'laal', 'लाल', 'ఎర్ర', 'செம்மண்', 'ಕೆಂಪು', 'ചുവന്ന', 'तांबಡಿ', 'तांबड्या'],
    sandy: ['sandy', 'sand', 'reti', 'retili', 'रेतीली', 'ఇసుక', 'மணல்', 'ಮರಳು', 'മണൽ', 'वालुकामय', 'रेತೀ'],
    clay: ['clay', 'chikni', 'चिकनी', 'బంకమట్టి', 'களிமண்', 'ಜೇಡಿ', 'കളിമണ്ണ്', 'चिकन', 'चिकण'],
    loamy: ['loamy', 'loam', 'domat', 'दोमट', 'లోమీ', 'வண்டல்', 'ಲೋಮಿ', 'പശിമരാശി', 'पोयटा', 'गाळाची'],
    alluvial: ['alluvial', 'jalodh', 'जलोढ़', 'ఒండ్రు', 'வண்டல்', 'ಮೆಕ್ಕಲು', 'എക്കൽ']
  },
  irrigation: {
    rainfed: ['rain', 'monsoon', 'barish', 'varsha', 'बारिश', 'वर्षा', 'వర్షాధార', 'மானாவாரி', 'ಮಳೆಯಾಶ್ರಿತ', 'മഴയെ', 'जिरायती', 'पावसावर', 'മഴ', 'మழை'],
    borewell: ['bore', 'tube', 'nal', 'tubewell', 'नलकूप', 'బోరు', 'ஆழ்துளை', 'ಬೋರ್', 'കുഴൽ', 'बोअरवेल', 'കുഴൽക്കിണർ'],
    canal: ['canal', 'nahar', 'नहर', 'కాలువ', 'கால்வாய்', 'ಕಾಲುವೆ', 'കനാൽ', 'कालवा'],
    well: ['well', 'kuwa', 'bavi', 'कुआँ', 'బావి', 'கிணறு', 'ಬಾವಿ', 'കിണർ', 'विहीर'],
    drip: ['drip', 'thibak', 'टपक', 'ड्रिप', 'బిందు', 'சொட்டு', 'ಹನಿ', 'ഡ്രിപ്പ്', 'ठिबक'],
    sprinkler: ['sprinkler', 'fawwara', 'फव्वारा', 'స్ప్రింక్లర్', 'தெளிப்பு', 'ತುಂತುರು', 'സ്പ്രിംഗ്ലർ', 'तुषार'],
    river: ['river', 'nadi', 'नदी', 'నది', 'நதி', 'ನದಿ', 'നദി']
  }
};

export const MOCK_CROPS: CropPrice[] = [
  { crop: "Wheat (Gehu)", price: 2125, minPrice: 2100, maxPrice: 2200, trend: "up", market: "Nagpur Mandi" },
  { crop: "Rice (Chawal)", price: 2800, minPrice: 2750, maxPrice: 2900, trend: "stable", market: "Nagpur Mandi" },
  { crop: "Cotton (Kapas)", price: 7200, minPrice: 7000, maxPrice: 7500, trend: "down", market: "Wardha Mandi" },
  { crop: "Soybean", price: 4800, minPrice: 4700, maxPrice: 4950, trend: "up", market: "Amravati Mandi" },
  { crop: "Onion", price: 1200, minPrice: 1000, maxPrice: 1500, trend: "up", market: "Lasalgaon" }
];

export const MOCK_ADVISORY = {
  [Language.ENGLISH]: "Your cotton crop is at Day 45 (Vegetative Stage). Soil moisture is adequate. It is recommended to spray Zinc Sulphate today to boost growth.",
  [Language.HINDI]: "आपकी कपास की फसल 45वें दिन (वानस्पतिक अवस्था) पर है। मिट्टी में नमी पर्याप्त है। विकास को बढ़ावा देने के लिए आज जिंक सल्फेट का छिड़काव करने की सलाह दी जाती है।",
  [Language.MARATHI]: "कपाशीचे पीक ४५ व्या दिवसावर आहे. जमिनीत ओलावा पुरेसा आहे. वाढीसाठी आज झिंक सल्फेट फवारण्याची शिफारस केली जाते.",
  [Language.TELUGU]: "మీరు పత్తి పంట 45వ రోజు (ఏపుగా పెరిగే దశ)లో ఉంది. నేలలో తేమ తగినంతగా ఉంది. పెరుగుదలను పెంచడానికి ఈ రోజు జింక్ సల్ఫేట్ పిచికారీ చేయాలని సిఫార్సు చేయబడింది.",
  [Language.TAMIL]: "உங்கள் பருத்தி பயிர் 45 வது நாளில் (தாவர நிலை) உள்ளது. மண்ணின் ஈரப்பதம் போதுமானது. வளர்ச்சியை அதிகரிக்க இன்று துத்தநாக சல்பேட்டைத் தெளிக்க பரிந்துரைக்கப்படுகிறது.",
  [Language.KANNADA]: "ನಿಮ್ಮ ಹತ್ತಿ ಬೆಳೆ 45 ನೇ ದಿನದಲ್ಲಿದೆ (ಸಸ್ಯಕ ಹಂತ). ಮಣ್ಣಿನ ತೇವಾಂಶ ಸಮರ್ಪಕವಾಗಿದೆ. ಬೆಳವಣಿಗೆಯನ್ನು ಹೆಚ್ಚಿಸಲು ಇಂದು ಸತು ಸಲ್ಫೇಟ್ ಸಿಂಪಡಿಸಲು ಶಿಫಾರಸು ಮಾಡಲಾಗಿದೆ.",
  [Language.MALAYALAM]: "നിങ്ങളുടെ പരുത്തി വിള 45-ാം ദിവസത്തിലാണ് (വളർച്ചാ ഘട്ടം). മണ്ണിന്റെ ഈർപ്പം മതിയാകും. വളർച്ച വർധിപ്പിക്കാൻ ഇന്ന് സിങ്ക് സൾഫേറ്റ് സ്പ്രേ ചെയ്യാൻ ശുപാർശ ചെയ്യുന്നു."
};

// Mock Soil Data (AgriStack Simulation)
export const SOIL_DATA = {
  nitrogen: "Medium",
  phosphorus: "Low",
  potassium: "High",
  pH: 7.2
};
